    openai_api_key = "none"
    openai_api_base = "http://localhost:1234/v1"  # Per LM Studio, se applicabile
    llm_model = "qwen2.5-coder-14b-instruct-mlx"
    llm_temperature = 0.2
    llm_optimization_level = "balanced"
    tools = "black,isort,pylint,flake8"
    exclude_tools = ""
    test_framework = "pytest"
    min_coverage = 80     # Minimum test coverage percentage required for the tests to pass.
    coverage_fail_action = "warn"